server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive # Force WebFlux
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # Fixed typo
      routes:
        - id: user-service-users
          uri: lb://user-service # Routes to user-service (port 8082)
          predicates:
            - Path=/users/**
        - id: sensor-data-service-api
          uri: lb://sensor-data-service # Routes to sensor-data-service (port 8081)
          predicates:
            - Path=/api/sensor-data**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true
    routes:
      enabled: true
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.web: DEBUG # For request handling